-- AlterTable
ALTER TABLE `creditors` ADD COLUMN `email` VARCHAR(191) NULL,
    ADD COLUMN `preferredChannel` ENUM('PHONE', 'EMAIL', 'FAX', 'MAIL', 'PORTAL', 'OTHER') NULL,
    ADD COLUMN `type` ENUM('ORIGINAL_CREDITOR', 'COLLECTION_AGENCY', 'LAW_FIRM', 'DEBT_BUYER', 'OTHER') NULL;
